  - name: Downloading java8
    get_url:
      url:  http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.rpm
      dest: /opt
      headers: "Cookie: oraclelicense=accept-securebackup-cookie"

  - name: Installing java8
    yum:
      name: /opt/jdk-8u102-linux-x64.rpm
      state: present

  #- name: Setting environment vars
    environment:
      JAVA_HOME: /usr/java/jdk1.8.0_102
      JRE_HOME: /usr/java/jdk1.8.0_102/jre

  - name: Installing elasticsearch
    yum:
      name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.rpm

  - name: Copy conf file
    copy:
      src: files/elasticsearch.yml
      dest: /etc/elasticsearch/elasticsearch.yml
      force: yes

  - name: Create directory
    file: path=/data state=directory owner=elasticsearch

  - name: Installing Kopf
    shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install lmenezes/elasticsearch-kopf/v2.1.2

  #- elasticsearch_plugin:
  #    state: present
  #    name: lmenezes/elasticsearch-kopf/
  #    version: '2.1.2'

  - shell: chkconfig --add elasticsearch

  - name: Starting service elasticsearch
    service:
      name: elasticsearch
      state: started
